### ISSUE TITLE
Missing Distro Files

### ISSUE THREAD

**Issue by zoffixznet** [cpanic/Data-SUID#1]
Hey,

It seems your last upload is missing all the files: https://metacpan.org/release/CPANIC/Data-SUID-1.000000

The only thing that got shipped are the two `META` files.

**Comment by cpanic** [comment]
Thanks for noticing that. MANIFEST borked. Much to learn ;-) 
1.000001 on its way.

**Comment by zoffixznet** [comment]
There are tools that can make releasing easier. Check out this article: http://shadow.cat/blog/matt-s-trout/mstpan-11/

I personally use [Dist::Zilla](http://dzil.org/) with [Dist::Zilla::PluginBundle::Author::ZOFFIX](https://metacpan.org/pod/Dist::Zilla::PluginBundle::Author::ZOFFIX)
